export const SECTION_ORDER = [
    'CHEF_COMPLIANT',
    'HISTORY_OF_PRESENT_ILLNESS',
    'REVIEW_OF_SYSTEMS',
    'PAST_MEDICAL_HISTORY',
    'PHYSICAL_EXAMINATION',
    'ASSESSMENT',
    'PLAN',
];
