export const SECTION_ORDER = [
    'CHIEF_COMPLIANT',
    'HISTORY_OF_PRESENT_ILLNESS',
    'PAST_MEDICAL_HISTORY',
    'PAST_FAMILY_HISTORY',
    'PAST_SOCIAL_HISTORY',
    'REVIEW_OF_SYSTEMS',
    'PHYSICAL_EXAMINATION',
    'DIAGNOSTIC_TESTING',
    'ASSESSMENT',
    'PLAN',
];
